########################################################################################################################
# Site Settings                                                                                                        #
########################################################################################################################

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://djsimtech.com" # the base hostname & protocol for your site, e.g. http://example.com

########################################################################################################################
# General settings                                                                                                     #
########################################################################################################################

lang: en
title: djsimtech
email: 

description: >- # this means to ignore newlines until "baseurl:"
  This blog is for random tech related posts. 

keywords: ['PowerShell', 'SCCM', 'pwsh', 'SysAdmin', 'Systems Administrator',
'DevOps', 'SRE']

logo: /assets/img/dannygalaxy_cropped.jpg

twitter_username: djsimtech
github_username:  djsimtech

# Build settings
theme: jekyll-theme-hydejack

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-seo-tag
  - jemoji

  # Share Links
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# Add links to the sidebar.
menu:
  - title: Blog
    url: /blog/
  - title: About
    url: /about/

# disqus: djsimtech

accent_image: /assets/img/glc.jpg
accent_color: rgb(79,177,186)
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

hydejack:
  # Configure the order of complementary content on blog posts
  post_addons: [about, newsletter, related, random, comments]

  # Code blocks and tables "break" the layout by spanning the full available width.
  # Set this to true if you want them to be the same width as other content.
  no_break_layout: true

  # Set to `true` to disable the dynamic Table of Contents on large screens.
  no_toc: false

  # When set to `true`, will not extend the content in the "third column" on large screens.
  # Instead, all content will remains within the center column.
  # Note that this will not affect the Table of Contents, use `no_toc` instead.
  no_third_column: false

links:
- https://twitter.com/djsimtech
- https://github.com/djsimtech
- https://www.linkedin.com/in/danny-simmons-3880162
