########################################################################################################################
# Site Settings                                                                                                        #
########################################################################################################################
url: "https://djsimtech.com/blog" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
########################################################################################################################
# General settings                                                                                                     #
########################################################################################################################

lang: en
title: djsimtech
description: >- # this means to ignore newlines until "baseurl:"
  This blog is for random tech related posts.
# email: 

 

keywords: ['PowerShell', 'SCCM', 'pwsh', 'SysAdmin', 'Systems Administrator',
'DevOps', 'SRE']

# A (square) logo for the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo: /assets/img/dannygalaxy_cropped.jpg

# This should be the same author as first entry in `_data/authors.yml`.
author1:
  name: Danny Simmons
  linkedin: danny-simmons-3880162
  twitter: djsimtech
  github: djsimtech
  email: 

# Share Links
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# Add links to the sidebar.
menu:
  - title: Blog
    url: /blog/
  - title: About
    url: /about/

# twitter_username: djsimtech
# github_username:  djsimtech

# Build settings
theme: jekyll-theme-hydejack

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-seo-tag
  - jemoji

copyright: ''

permalink: /blog/:title

########################################################################################################################
# Jekyll Customizations                                                                                                #
########################################################################################################################

# Sidebar image and theme color of the site.
accent_image: /assets/img/glc.jpg
accent_color: rgb(79,177,186)

# This is used for the `theme-color` meta tag,
# which changes the background color of the browser UI in certain browsers.
# Defaults to `accent_color`.
theme_color: rgb(8,46,57)

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

hydejack:
  # Configure the order of complementary content on blog posts
  post_addons: [about, newsletter, related, random, comments]

  # Code blocks and tables "break" the layout by spanning the full available width.
  # Set this to true if you want them to be the same width as other content.
  no_break_layout: true

  # Set to `true` to disable the dynamic Table of Contents on large screens.
  no_toc: false

  # When set to `true`, will not extend the content in the "third column" on large screens.
  # Instead, all content will remains within the center column.
  # Note that this will not affect the Table of Contents, use `no_toc` instead.
  no_third_column: false

links:
- https://twitter.com/djsimtech
- https://github.com/djsimtech
- https://www.linkedin.com/in/danny-simmons-3880162
